// vue/src/components/Spinner.vue
<template>
  <div id="loader1" class="centered">
    <div class="centeredBorder">

      <div class="centered1">

      </div>
    </div>
  </div>
</template>

<script>

export default {
  name: 'Spinner',
  props: {
    enable: Boolean
  },
  data() {
    return {
      enable: true
    }
  }
}
</script>

// react/ammortization/src/components/Spinner/Spinner.tsx
import React, { Component } from 'react';
import './Spinner.css'

export default class Spinner extends Component {

    render(){

        return (
        <div id="loader1" className="centered">
        <div className="centeredBorder">
    
          <div className="centered1">
          </div>
        </div>
      </div>
        )
    }
}
